export function buildDeliveryStagedPanelProps({
  sortedStagedDeliveries,
  sortedProjectedDeliveries,
  stores,
  patients,
  currentUser,
  editingStagedId,
  isMobileDevice,
  handleStagedDeliveryClick,
  handleClearForm,
  stagedDeliveries,
  fullPredictionListRef,
  setProjectedDeliveries,
  setStagedDeliveries,
  setEditingStagedId,
  patientSearchInputRef,
  confirmAddProjectedToStaged,
  setDeleteConfirmation,
  isLoadingPredictions,
  handleRefreshProjections,
  shouldAutoFocusFields,
  selectedDate
}) {
  return {
    sortedStagedDeliveries,
    sortedProjectedDeliveries,
    stores,
    patients,
    currentUser,
    editingStagedId,
    isMobileDevice,
    handleStagedDeliveryClick,
    handleClearForm,
    stagedDeliveries,
    fullPredictionListRef,
    setProjectedDeliveries,
    setStagedDeliveries,
    setEditingStagedId,
    patientSearchInputRef,
    confirmAddProjectedToStaged,
    setDeleteConfirmation,
    isLoadingPredictions,
    onRefreshProjections: handleRefreshProjections,
    shouldAutoFocusFields,
    selectedDate
  };
}