export default function getDriverRouteControlsProps({
  setShowAllDriverMarkers,
  shouldShowLocationToggle,
  currentUser,
  refreshUser,
  isDriver,
  setShowQuickAdjustments,
  setShowSmartPrioritization,
  appUsers,
  preferredTravelMode,
  setPreferredTravelMode,
  isRouteComplete,
  modeDialogOpen,
  setModeDialogOpen,
  nearbyModeStops,
  selectedModeStopIds,
  toggleModeStop,
  returnToCurrentLocation,
  toggleReturnToCurrentLocation,
  handleModeOptimize,
  isOptimizingModeRoute,
}) {
  return {
    setShowAllDriverMarkers,
    shouldShowLocationToggle,
    currentUser,
    refreshUser,
    isDriver,
    setShowQuickAdjustments,
    setShowSmartPrioritization,
    appUsers,
    preferredTravelMode,
    setPreferredTravelMode,
    hasActiveRoute: !isRouteComplete,
    modeDialogOpen,
    setModeDialogOpen,
    nearbyModeStops,
    selectedModeStopIds,
    toggleModeStop,
    returnToCurrentLocation,
    toggleReturnToCurrentLocation,
    handleModeOptimize,
    isOptimizingModeRoute,
  };
}