import { base44 } from '@/api/base44Client';
import { format } from 'date-fns';
import { invalidate } from '@/components/utils/dataManager';
import { offlineDB } from '@/components/utils/offlineDatabase';

/**
 * Quick Adjust reorder: persists the new stop_order from the drag, then runs
 * optimizeRemainingStops with preserveExistingOrder=true so ETAs are recalculated
 * from the driver's live GPS position using the same logic as the manual FAB.
 * New polylines are regenerated via regenerateType1Polyline after ETAs are set.
 */
export async function handleQuickReorder(reorderUpdates, selectedDate, currentUser, updateDeliveryLocal, { appUsers } = {}) {
  const deliveryDate = format(selectedDate, 'yyyy-MM-dd');

  // 1. Persist the new stop_order values that the user dragged into place
  for (const update of reorderUpdates) {
    await updateDeliveryLocal(update.id, { stop_order: update.stop_order });
  }

  // 2. Recalculate ETAs (preserving the new order) via client-side engine
  const { performRouteOptimization } = await import('@/components/utils/routeOptimizationCoordinator');
  await performRouteOptimization({
    driverId: currentUser.id,
    deliveryDate,
    preserveExistingOrder: true,
    bypassDriverStatus: true,
    source: 'quick_reorder',
  });

  // 3. Polylines are already regenerated by performRouteOptimization above (preserveExistingOrder: true)
  // No separate backend call needed — the client-side engine handles polyline generation.

  // 4. Refresh UI with fresh data
  invalidate('Delivery');
  const freshDeliveries = await base44.entities.Delivery.filter({
    driver_id: currentUser.id,
    delivery_date: deliveryDate
  });

  if (Array.isArray(freshDeliveries) && freshDeliveries.length > 0) {
    await Promise.all(freshDeliveries.map(d => offlineDB.save(offlineDB.STORES.DELIVERIES, d).catch(() => {})));
  }

  window.dispatchEvent(new CustomEvent('deliveriesUpdated', {
    detail: {
      triggeredBy: 'quickReorder',
      freshDeliveries,
      fullReplacement: false,
    }
  }));
}