/**
 * useWebUpdateCheck — polls /version.json every 5 minutes and compares the
 * build ID against the one baked into this loaded bundle. A mismatch means
 * a new deploy was pushed to the server. Returns { hasUpdate, buildId }.
 *
 * The build ID is injected at build time via Vite's `define` config:
 *   __WEB_BUILD_ID__ = "<git-sha-short>"
 *
 * version.json is generated by scripts/generate-version.mjs before each
 * `vite build` and served as a static file from public/.
 *
 * Cache-busting query param ensures the CDN doesn't serve a stale copy.
 */
import { useState, useEffect, useRef } from 'react';

const POLL_INTERVAL = 5 * 60 * 1000; // 5 minutes

// Fallback if the define didn't run (dev mode, etc.)
const BUILT_BUILD_ID = typeof __WEB_BUILD_ID__ !== 'undefined' ? __WEB_BUILD_ID__ : 'dev';

export function useWebUpdateCheck() {
  const [hasUpdate, setHasUpdate] = useState(false);
  const [currentBuildId, setCurrentBuildId] = useState(null);
  const mountedRef = useRef(true);

  useEffect(() => {
    mountedRef.current = true;
    let timer = null;
    let cancelled = false;

    const check = async () => {
      try {
        const resp = await fetch(`/version.json?cb=${Date.now()}`, {
          cache: 'no-store',
          headers: { 'Cache-Control': 'no-cache' },
        });
        if (!resp.ok) return;
        const data = await resp.json();
        if (cancelled || !mountedRef.current) return;

        const serverBuildId = data?.buildId;
        if (!serverBuildId) return;

        setCurrentBuildId(serverBuildId);

        // Mismatch = server has a newer build than what's loaded
        if (BUILT_BUILD_ID !== 'dev' && serverBuildId !== BUILT_BUILD_ID) {
          setHasUpdate(true);
        }
      } catch {
        // Network error or version.json not found — silent, no badge
      }
    };

    // Delay first check 10s after mount to avoid competing with boot
    const delayTimer = setTimeout(() => {
      check();
      timer = setInterval(check, POLL_INTERVAL);
    }, 10_000);

    return () => {
      cancelled = true;
      mountedRef.current = false;
      clearTimeout(delayTimer);
      if (timer) clearInterval(timer);
    };
  }, []);

  return { hasUpdate, currentBuildId, builtBuildId: BUILT_BUILD_ID };
}
